<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Student Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 10px;
            margin: 10px;
        }

        .header {
            display: flex;
            align-items: center;
            justify-content: center;
            position: relative;
            margin-bottom: 10px;
            height: 80px;
        }

        .header .logo {
            position: absolute;
            left: 0;
            width: 50px;
            height: auto;
        }

        .header-text {
            text-align: center;
        }

        .header-text h1,
        .header-text p {
            margin: 0;
            font-size: 12px;
        }

        .info-box {
            border: 1px solid #000;
            padding: 5px;
            margin-bottom: 10px;
        }

        .info-box table {
            width: 100%;
            border-collapse: collapse;
        }

        .info-box td {
            padding: 2px;
        }

        .student-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        .student-table th,
        .student-table td {
            border: 1px solid #000;
            text-align: center;
            padding: 4px;
            font-size: 9px;
        }

        .student-table th {
            background-color: #f2f2f2;
            font-weight: bold;
        }
    </style>
</head>

<body>
    <div class="header">
        <img src="data:image/png;base64,{{ base64_encode(file_get_contents(public_path('assets/img/logo.png'))) }}"
            alt="Logo" class="logo">
        <div class="header-text">
            <h1>Bukidnon State University</h1>
            <p>Malaybalay City, Bukidnon 6700</p>
            <p>Tel: (088) 813-5661 to 5663, Telefax: (088) 813-2717</p>
            <p>www.buksu.edu.ph</p>
        </div>
    </div>

    <div class="info-box">
        <table>
            <tr>
                <td><strong>Generated By:</strong> {{ $generatedBy->full_name }}</td>
                <td><strong>Role:</strong> {{ $generatedBy->role->name }}</td>
            </tr>
            @if ($collegeFilter)
                <tr>
                    <td colspan="2"><strong>College Filter:</strong> {{ $collegeFilter->name }}</td>
                </tr>
            @endif
            @if ($departmentFilter)
                <tr>
                    <td colspan="2"><strong>Department Filter:</strong> {{ $departmentFilter->name }}</td>
                </tr>
            @endif
            @if ($sectionFilter)
                <tr>
                    <td colspan="2"><strong>Section Filter:</strong> {{ $sectionFilter->name }}</td>
                </tr>
            @endif
            @if ($yearLevelFilter)
                <tr>
                    <td colspan="2"><strong>Year Level Filter:</strong> {{ $yearLevelFilter }}</td>
                </tr>
            @endif
        </table>
    </div>

    <table class="student-table">
        <thead>
            <tr>
                <th>#</th>
                <th>Username</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Email</th>
                <th>Role</th>
                <th>College</th>
                <th>Department</th>
                <th>Section</th>
                <th>Year Level</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($students as $index => $student)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $student->username }}</td>
                    <td>{{ $student->first_name }}</td>
                    <td>{{ $student->last_name }}</td>
                    <td>{{ $student->email }}</td>
                    <td>{{ optional($student->role)->name }}</td>
                    <td>{{ optional($student->college)->name }}</td>
                    <td>{{ optional($student->department)->name }}</td>
                    <td>{{ optional($student->section)->name }}</td>
                    <td>{{ optional($student->section)->year_level }}</td>
                    <td>{{ ucfirst($student->status) }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="11">No students found.</td>
                </tr>
            @endforelse
        </tbody>
    </table>
</body>

</html>
