<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Subject Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 10px;
            font-size: 9px;
        }

        .pdf-wrapper {
            width: 100%;
        }

        .header {
            display: flex;
            align-items: center;
            justify-content: center;
            position: relative;
            margin-bottom: 10px;
            height: 80px;
        }

        .header .logo {
            position: absolute;
            left: 0;
            width: 60px;
            height: auto;
        }

        .header-text {
            text-align: center;
        }

        .header-text h1,
        .header-text p {
            margin: 0;
            font-size: 15px;
        }

        .info-box {
            border: 1px solid #000;
            padding: 5px;
            margin-bottom: 5px;
        }

        .info-box table {
            width: 100%;
            border-collapse: collapse;
        }

        .info-box td {
            padding: 2px;
        }

        .subject-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        .subject-table th,
        .subject-table td {
            border: 1px solid #000;
            text-align: left;
            padding: 2px;
            font-size: 10px;
        }

        .subject-table th {
            background-color: #f2f2f2;
        }

        .college-header {
            font-size: 11px;
            font-weight: bold;
            margin-top: 10px;
            text-transform: uppercase;
        }

        .department-header {
            font-size: 10px;
            font-weight: bold;
            margin-top: 5px;
            text-transform: uppercase;
        }
    </style>
</head>

<body>
    <div class="pdf-wrapper">
        <div class="header">
            <img src="data:image/png;base64,{{ base64_encode(file_get_contents(public_path('assets/img/logo.png'))) }}"
                alt="Logo" class="logo" />
            <div class="header-text">
                <h1>Bukidnon State University</h1>
                <p>Malaybalay City, Bukidnon 6700</p>
                <p>Tel: (088) 813-5661 to 5663, Telefax: (088) 813-2717</p>
                <p>www.buksu.edu.ph</p>
            </div>
        </div>

        <div class="info-box">
            <table>
                <tr>
                    <td><strong>Generated By:</strong> {{ $generatedBy }}</td>
                </tr>
                <tr>
                    <td><strong>College Filter:</strong> {{ $collegeFilter }}</td>
                    <td><strong>Department Filter:</strong> {{ $departmentFilter }}</td>
                </tr>
            </table>
        </div>

        @foreach ($colleges as $college)
            <div class="college-header">{{ $college->name }}</div>
            @foreach ($college->departments as $department)
                <div class="department-header">Department: {{ $department->name }}</div>
                <table class="subject-table">
                    <thead>
                        <tr>
                            <th>Subject Code</th>
                            <th>Subject Name</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse ($department->subjects as $subject)
                            <tr>
                                <td>{{ $subject->code }}</td>
                                <td>{{ $subject->name }}</td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="2">No subjects found for this department.</td>
                            </tr>
                        @endforelse
                    </tbody>
                </table>
            @endforeach
        @endforeach
    </div>
</body>

</html>
