<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 10px;
            margin: 10px;
            /* Reduced margin to maximize usable space */
        }

        .pdf-wrapper {
            transform: scale(1);
            /* Removed scaling to ensure proper usage of the space */
            transform-origin: top left;
            width: 100%;
            /* Ensure full-width utilization */
        }

        .header {
            display: flex;
            align-items: center;
            justify-content: center;
            position: relative;
            margin-bottom: 10px;
            /* Reduced to save space */
            height: 80px;
            /* Adjusted height to be more compact */
        }

        .header .logo {
            position: absolute;
            left: 0;
            width: 50px;
            /* Slightly smaller logo */
            height: auto;
        }

        .header-text {
            text-align: center;
        }

        .header-text h1,
        .header-text p {
            margin: 0;
            font-size: 12px;
            /* Adjusted font size for better fit */
        }

        .info-box {
            border: 1px solid #000;
            padding: 5px;
            margin-bottom: 10px;
            /* Reduced spacing below the info box */
        }

        .info-box table {
            width: 100%;
            border-collapse: collapse;
        }

        .info-box td {
            padding: 2px;
        }

        .dtr-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
            /* Reduced spacing above the table */
        }

        .dtr-table th,
        .dtr-table td {
            border: 1px solid #000;
            text-align: center;
            padding: 4px;
            /* Adjusted padding to fit more rows */
            font-size: 9px;
            /* Slightly smaller font size for rows */
        }

        .dtr-table th {
            background-color: #f2f2f2;
            font-weight: bold;
        }
    </style>


</head>

<body>
    <div class="pdf-wrapper">
        <div class="header">
            <img src="data:image/png;base64,{{ base64_encode(file_get_contents(public_path('assets/img/logo.png'))) }}"
                alt="Logo" class="logo">
            <div class="header-text">
                <h1>Bukidnon State University</h1>
                <p>Malaybalay City, Bukidnon 6700</p>
                <p>Tel: (088) 813-5661 to 5663, Telefax: (088) 813-2717</p>
                <p>www.buksu.edu.ph</p>
            </div>
        </div>

        <div class="info-box">
            <table>
                <tr>
                    <td><strong>Generated By:</strong> {{ $user->full_name }}</td>
                    <td><strong>Role:</strong> {{ $user->role->name }}</td>
                </tr>
                <tr>
                    @if ($role)
                        <td><strong>Role Filter:</strong> {{ ucfirst($role) }}</td>
                    @endif
                    @if ($status)
                        <td><strong>Status Filter:</strong> {{ ucfirst($status) }}</td>
                    @endif
                </tr>
            </table>
        </div>

        <table class="dtr-table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Username</th>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Email</th>
                    <th>Role</th>
                    <th>College</th>
                    <th>Department</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                @forelse ($users as $index => $user)
                    <tr>
                        <td>{{ $index + 1 }}</td>
                        <td>{{ $user->username }}</td>
                        <td>{{ $user->first_name }}</td>
                        <td>{{ $user->last_name }}</td>
                        <td>{{ $user->email }}</td>
                        <td>{{ optional($user->role)->name }}</td>
                        <td>{{ optional($user->college)->name }}</td>
                        <td>{{ optional($user->department)->name }}</td>
                        <td>{{ ucfirst($user->status) }}</td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="9">No users found.</td>
                    </tr>
                @endforelse
            </tbody>
        </table>
    </div>
</body>

</html>
